server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA routing — tout renvoie vers index.html (React Router gère les routes)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Pas de proxy /api/ ici : le browser appelle directement http://localhost (gateway port 80)
    # Le gateway nginx tourne dans son propre container et gère le routing vers les microservices
}
