server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA routing — tout renvoie vers index.html (React Router gère les routes)
    location / {
        try_files $uri $uri/ /index.html;
    }

}
