server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API — pointe vers le gateway nginx (résolvable depuis Docker network)
    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $gateway http://nginx;
        proxy_pass $gateway/api/;
        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
